Models/Staff.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BigVisionGames.Models
{
    public class Staff : User
    {
        //nav props
        //public List<Order> Orders { get; set; }
    }
}

Models/Supplier.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BigVisionGames.Models
{
    public class Supplier
    {
        [Key]
        public int SupplierId { get; set; }
        public string SupplierName { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string Website { get; set; }

        //nav props
        public List<Product> Products { get; set; }

    }
}

Controllers/StaffController.cs
using BigVisionGames.Models;
using BigVisionGames.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BigVisionGames.Controllers
{
    public class StaffController : Controller
    {
        // GET: Staff
        private BVGDbContext context = new BVGDbContext();
        /// <summary>
        /// Displays all products along with their supplier
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            //list all products along with their supplier
            var products = context.Products.Include(p => p.Supplier);
            return View(products.ToList());
        }
        public ActionResult Suppliers()
        {
            //list all products along with their supplier
            var suppliers = context.Suppliers.ToList();
            return View(suppliers);
        }

        /// <summary>
        /// Displays detaisl of the selected product
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Details(int id)
        {
            //find the selected product in the db
            Product product = context.Products.Find(id);
            //include the supplier
            var supplier = context.Suppliers.Find(product.SupplierId);
            //find the supplier
            product.Supplier = supplier;
            return View(product);
        }

        /// <summary>
        /// Displays all previous confirmed orders
        /// </summary>
        /// <returns></returns>
        public ActionResult AllOrders()
        {
            //get all previous confirmed orders
            var orders = context.Orders.Where(o => o.OrderStatus == OrderStatus.Complete).Include(o => o.OrderLines).Include(o => o.Customer).OrderByDescending(o=>o.OrderDate).ToList();
            return View(orders);
        }
        /// <summary>
        /// Displays the details of the selected order
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult AllOrderDetails(int id)
        {
            //find the order
            Order order = context.Orders.Find(id);
            //get the orders orderlines
            order.OrderLines = context.OrderLines.Where(o => o.OrderId == order.OrderId).Include(o => o.Product).ToList();
            //display the order using a viewmodel
            var viewmodel = new BasketViewModel()
            {
                Order = order,
                orderlines = order.OrderLines,
                orderTotal = order.OrderTotal
            };
            return View(viewmodel);
        }

    }
}

Views/Staff/AllOrderDetails.cshtml
@model BigVisionGames.ViewModels.BasketViewModel

<link href="~/StyleSheet.css" rel="stylesheet" />


<h1>Order #@Model.Order.OrderId Details</h1>

<table class="table">

    @foreach (var item in Model.orderlines)
    {
        <tr>
            <th>
                @Html.DisplayNameFor(modelItem => item.Product.ProductName)
            </th>
            <th>
                @Html.DisplayNameFor(modelItem => item.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(modelItem => item.LineTotal)
            </th>
        </tr>
        break;

    }



    @foreach (var item in Model.orderlines)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Product.ProductName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                £@Html.DisplayFor(modelItem => item.LineTotal)
            </td>
        </tr>

    }

</table>
<p style="margin-top:50px; font-weight:700; font-size:large; margin-left: 995px; margin-bottom:20px">
    @Html.DisplayNameFor(model => model.orderTotal) &nbsp;
    £@Html.DisplayFor(model => model.orderTotal)
</p>
<div>
    @Html.ActionLink("Back", "AllOrders", "Staff", null, new {@class= "button"})
</div>

Views/Staff/AllOrders.cshtml
@model IEnumerable<BigVisionGames.Models.Order>

<link href="~/StyleSheet.css" rel="stylesheet" />



<h2>All Orders</h2>

<table class="table">

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <div style="font-size:large">
                    Order #@Html.DisplayFor(modelItem => item.OrderId)
                </div>
                <div style="font-weight: bold">
                    £@Html.DisplayFor(modelItem => item.OrderTotal)
                </div>
            </td>
            <td>@Html.DisplayFor(modelItem => item.OrderDate)</td>
            <td>
                @Html.ActionLink("Details", "AllOrderDetails", new { id = item.OrderId }, new { @class = "button" })
            </td>
        </tr>
    }

</table>

@if (!Model.Any())
{
    <p style="font-size:larger; font-weight:bold">No Orders</p>
}

Views/Staff/Details.cshtml
@model BigVisionGames.Models.Product

<link href="~/StyleSheet.css" rel="stylesheet" />

<a href="@Html.DisplayFor(model => model.ImageLink)" target="_blank" title="View Image"><h2 class="productname">@Model.ProductName </h2></a>

<div>
    <div style="font-size:large;">
        £@Html.DisplayFor(model => model.Price)
    </div>
    @Html.DisplayFor(model => model.Description).
    <br>
    Stock Level: @Html.DisplayFor(model => model.StockLevel)
    <br />
    Supplier: @Html.DisplayFor(model => model.Supplier.SupplierName)
    <br />
    <br />
</div>

<div>
    @Html.ActionLink("Home", "Index", null, new { @class = "button" })
</div>

Views/Staff/Index.cshtml
@model IEnumerable<BigVisionGames.Models.Product>

<link href="~/StyleSheet.css" rel="stylesheet" />


<h2>BVG Products</h2>

<table class="table">


    @foreach (var item in Model)
    {
        <tr>
            <td>
                <div style="font-size:x-large">
                    @Html.DisplayFor(modelItem => item.ProductName)
                </div>
                £@Html.DisplayFor(modelItem => item.Price)
                <br />
                @if (item.StockLevel < 10 && item.StockLevel >= 1 )
                {
                    <span style="color: red">
                        Stock: @Html.DisplayFor(modelItem => item.StockLevel)
                    </span>
                }
                else if (item.StockLevel == 0)
                {
                    <span style="color: red">
                        Out of Stock
                    </span>
                }
                else if (item.StockLevel >= 10 && item.StockLevel < 25)
                {
                    <span style="color: #b6a025">
                        Stock: @Html.DisplayFor(modelItem => item.StockLevel)
                    </span>
                }
                else if (item.StockLevel >= 25)
                {
                    <span style="color: forestgreen">
                        Stock: @Html.DisplayFor(modelItem => item.StockLevel)
                    </span>
                }
            </td>
            <td>
                @Html.ActionLink("View", "Details", new { id = item.ProductId }, new { @class = "button" })
            </td>

        </tr>
    }



</table>

Views/Staff/Suppliers.cshtml
@model IEnumerable<BigVisionGames.Models.Supplier>

<h2>BVG Suppliers</h2>

<table class="table">

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <div style="font-weight: bold">
                    @Html.DisplayFor(modelItem => item.SupplierName)
                </div>
                @Html.DisplayFor(modelItem => item.Address)
                <br />
                @Html.DisplayFor(modelItem => item.PhoneNumber)
                <br />
                <a href="@Html.DisplayFor(modelItem => item.Website)" target="_blank">Visit Website</a>
            </td>

        </tr>
    }

</table>

<div>
    @Html.ActionLink("Home", "Index", null, new { @class = "button" })
</div>